services:
  server:
    build:
      context: .
    container_name: CraftConnect-App
    image: craftconnect-app:latest
    ports:
      - "8080:8080"
    networks:
      - s-network
    depends_on:
        mysql:
          condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: CraftConnect-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: CraftConnect
      MYSQL_USER: CraftConnect-MySQL
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - s-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  s-network:
    driver: bridge